---
- name: create the main server user
  user:
    name: main-server
    groups:
      - audio
      - video
    shell: /bin/bash

- name: install main server apt dependencies
  apt:
    name:
      - vim
      - git
      - python3
      - python3-pip
      - awscli
      - ffmpeg
      # openCV devepencies
      - libatlas3-base
      - libjasper-dev
      - libopencv-dev
      - libgstreamer1.0-dev
      - libqtgstreamer-dev
    update_cache: yes

- name: update awscli using pip
  pip:
    name: awscli
    state: latest
    executable: /usr/bin/pip3

- name: create aws directory
  file:
    path: /home/main-server/.aws
    state: directory
    owner: main-server
    group: main-server

- name: copy aws config
  copy:
    src: "{{ playbook_dir }}/secrets/aws/config"
    dest: "/home/main-server/.aws/config"
    owner: main-server
    group: main-server
    mode: 0400

- name: copy aws credentials
  copy:
    src: "{{ playbook_dir }}/secrets/aws/credentials"
    dest: "/home/main-server/.aws/credentials"
    owner: main-server
    group: main-server
    mode: 0400

- name: install main server python dependencies
  pip:
    name:
      - flask
      - pytz
      # This one takes a long time > 10 mins
      - opencv-python
    state: latest
    executable: /usr/bin/pip3

- name: create main server directory
  file:
    path: /home/main-server/main-server
    state: directory
    owner: main-server
    group: main-server

- name: copy main server module
  copy:
    src: "{{ playbook_dir }}/../main-server/main_server.py"
    dest: "/home/main-server/main-server/main_server.py"
    owner: main-server
    group: main-server
  notify:
    - restart main-server

- name: copy camera module
  copy:
    src: "{{ playbook_dir }}/../main-server/home_alert_camera.py"
    dest: "/home/main-server/main-server/home_alert_camera.py"
    owner: main-server
    group: main-server
  notify:
    - restart main-server

- name: copy smtp info
  copy:
    src: "{{ playbook_dir }}/secrets/smtp_info.json"
    dest: "/home/main-server/main-server/smtp_info.json"
    owner: main-server
    group: main-server
    mode: 0600
  notify:
    - restart main-server

- name: copy main-server systemd service unit file
  copy:
    src: "main-server.service"
    dest: "/etc/systemd/system/main-server.service"
  notify:
    - restart main-server
