---
- name: create the main server user
  user:
    name: main-server
    groups:
      - audio
      - video
    shell: /bin/bash

- name: install main server apt dependencies
  apt:
    name:
      - vim
      - git
      - python3
      - awscli
      - ffmpeg
      # openCV devepencies
      - libatlas3-base
      - libjasper-dev
      - libopencv-dev
      - libgstreamer1.0-dev
      - libqtgstreamer-dev
    update_cache: yes

# Have to use get-pip.py as apt's version throws errors.
# See https://stackoverflow.com/questions/37495375/python-pip-install-throws-typeerror-unsupported-operand-types-for-retry
- name: install pip using get-pip.py
  script: install_pip.sh

- name: update awscli using pip
  pip:
    name: awscli
    state: latest
    executable: /usr/local/bin/pip3

- name: create aws directory
  file:
    path: /home/main-server/.aws
    state: directory
    owner: main-server
    group: main-server

- name: copy aws config
  copy:
    src: "{{ playbook_dir }}/secrets/aws/config"
    dest: "/home/main-server/.aws/config"
    owner: main-server
    group: main-server
    mode: 0400

- name: copy aws credentials
  copy:
    src: "{{ playbook_dir }}/secrets/aws/credentials"
    dest: "/home/main-server/.aws/credentials"
    owner: main-server
    group: main-server
    mode: 0400

- name: install main server python dependencies
  pip:
    name:
      - flask
      - pytz
      # This one takes a long time > 10 mins
      - opencv-python
    state: latest
    executable: /usr/local/bin/pip3

- name: create photos directory
  file:
    path: /home/main-server/photos/door_front
    state: directory
    owner: main-server
    group: main-server

- name: create main server directory
  file:
    path: /home/main-server/main-server
    state: directory
    owner: main-server
    group: main-server

- name: copy main server python code
  copy:
    src: "{{ playbook_dir }}/../main-server/python/"
    dest: "/home/main-server/main-server/python/"
    owner: main-server
    group: main-server
  notify:
    - restart main-server

- name: create main server secrets directory
  file:
    path: /home/main-server/main-server/secrets
    state: directory
    owner: main-server
    group: main-server

- name: copy smtp info
  copy:
    src: "{{ playbook_dir }}/secrets/smtp_info.json"
    dest: "/home/main-server/main-server/secrets/smtp_info.json"
    owner: main-server
    group: main-server
    mode: 0600
  notify:
    - restart main-server

- name: copy main-server systemd service unit file
  copy:
    src: "main-server.service"
    dest: "/etc/systemd/system/main-server.service"
  notify:
    - restart main-server
