- name: install reverse proxy server and dependencies
  apt:
    name:
      - vim
      - bind9
      - nginx
      # Needed for ssl
      - apache2-utils
    update_cache: yes

# Bind9 needed to resolve names for reverse proxy
- name: ensure bind9 service is running
  service:
    daemon_reload: yes
    name: bind9.service
    enabled: yes
    state: started

- name: copy home-alert nginx site config from template
  template:
    src: home-alert-control-site.j2
    dest: /etc/nginx/sites-available/home-alert-control-site
    owner: root
    group: root
    mode: 0644
  notify:
    restart nginx

- name: link home-alert nginx site config from available to enabled 
  file:
    src: /etc/nginx/sites-available/home-alert-control-site
    dest: /etc/nginx/sites-enabled/home-alert-control-site
    state: link 
  notify:
    restart nginx

- name: create home alert www directory
  file:
    path: "/var/www/html/home-alert"
    state: directory
    owner: root
    group: root


- name: copy index.html from template
  template:
    src: index.html.j2
    dest: /var/www/html/home-alert/index.html
    owner: root
    group: root
    mode: 0644

- name: copy all_streams.html from template
  template:
    src: all_streams.html.j2
    dest: /var/www/html/home-alert/all_streams.html
    owner: root
    group: root
    mode: 0644

- name: copy htpasswd file
  copy:
    src: htpasswd
    dest: /etc/nginx/.htpasswd
    owner: www-data
    group: www-data
    mode: 0400

# public key for file in roles/home-alert-node/files/id_rsa
- name: Set authorized key from file
  authorized_key:
    user: "{{ control_server.user }}"
    state: present
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCHRARAVsG8IglUK7fZudf85mzMHwIsyyZY9EePjIOtxuHRyf59/h0XDITS8/d2ldmW1tpqYWENVhsg+5CNxU80X5MgVUyo9H1XwGaQlmxdDkawQmQvByVkwijyTGr4LNKCAwgRvo8Uw+Y/rwuEH7PxMoXD9D7jFNOmX/WFOK8UgvXNoQ/7CnZTgUj6TplD0JyBpPNZyHrPmWmhJ6voo936NOtRTYpccim5VZ9TDxhG48BwH4a/uOYlAQ8PGxJf9eJBVxTzyChlsZnlWR6NPd/P/noiTfwOqCPJlT+ZUJ8Z1wAlykWNKep+iqGGKIVkNfM+De9XneZMK9G/RuP5nyXfckA6ZPEmY4s0nnW2REktIPmoLCs12uhsQdtsqLuic9ApomuRuDgCAThu+Yf1WNYFpmp4Mwxw7T5BALmukFxsyzvBHahSi5wycWgExGVGK0414uSbQ8d2WlFuZ9tek+zxY245VoAbSgORLGUJFYiOSSnOf9Jn4dZYDkbkeAFtTCk= home-alert-node"
