- name: install reverse proxy server and dependencies
  package:
    name:
      - nginx
    update_cache: yes

- name: copy home-alert nginx site config from template
  template:
    src: home-alert-control-site.j2
    dest: /etc/nginx/home-alert-control-site.conf
    owner: root
    group: root
    mode: 0644
  notify:
    restart nginx

- name: create home alert www directory
  file:
    path: "/var/www/html/home-alert"
    state: directory
    owner: root
    group: root


- name: copy index.html from template
  template:
    src: index.html.j2
    dest: /var/www/html/home-alert/index.html
    owner: root
    group: root
    mode: 0644

- name: copy all_streams.html from template
  template:
    src: all_streams.html.j2
    dest: /var/www/html/home-alert/all_streams.html
    owner: root
    group: root
    mode: 0644

- name: copy htpasswd file
  copy:
    src: htpasswd
    dest: /etc/nginx/.htpasswd
    owner: nginx
    group: nginx
    mode: 0400

- name: Set authorized key from file
  authorized_key:
    user: "{{ control_server.user }}"
    state: present
    key: "{{ lookup('file', 'vars/id_rsa.pub') }}"
