---
# This is the main configuration file for the entire Home Alert system.
# Users should not have to manually edit any other files in this repo but this one.

# WiFi Credentials
wifi:
  ssid: "ssid"
  password: "password"

# Control Server
control_server:
  address: "10.0.0.138"
  user: "pi"
  web_credentials:
    # Can have multiple logins to the control server
    - username: "admin"
      password: "admin"

# List of emails to send notifications when a location is triggered.
notify_emails:
  - "sato@naookie.com"

# Main Server Definitions
main_servers:
  # Each element in this list defines a main server. Add elements to define multiple main servers.
  - location: "front_door"
    address: "10.0.0.138"
    server_port: 5000
    user: "pi"
    video_device: "/dev/video0"
    video_width: 1280
    video_height: 720
    # opencv_install may be one of
    # apt: install opencv python3 bindings using apt, not available on all distributions.
    # source: Download and compile opencv and python3 bindings, can take **hours**.
    # stretch: Use a combination of apt and pip to get working python3 bindings on raspian stretch
    # skip: you have installed opencv on your own, do not attempt any installation method.
    #
    # If using source on a raspberry pi, you must have a swap partition set up.
    # Otherwise you will risk running out of ram during compilation.
    opencv_install: "skip"

# Email to send notifications
smtp_info:
  host: "smtp.gmail.com"
  port: 587
  user_address: "example@gmail.com"
  user_pass: "password"

# S3 bucket to upload, optional. Either an s3 url ("s3://com.mybucket/") or null
# If defined, all captured media will be uploaded to this bucket.
s3_upload_bucket: null
