---
- name: create the rtsp streaming server user
  user:
    name: rtsp-server
    shell: /bin/bash

- name: rtsp-server package dependencies
  apt:
    update_cache: yes
    name:
      - git
      - libmoose-perl
      - liburi-perl
      - libmoosex-getopt-perl
      - libsocket6-perl
      - libanyevent-perl
      - ffmpeg

- name: clone the rtsp-server repo
  git:
    repo: 'https://github.com/revmischa/rtsp-server.git'
    dest: '/home/rtsp-server/rtsp-server'
  become: yes
  become_user: rtsp-server

- name: run rtsp-server perl Makefile.PL
  shell: 'cd /home/rtsp-server/rtsp-server && perl Makefile.PL'
  become: yes
  become_user: rtsp-server

- name: make rtsp-server
  make: 
    chdir: '/home/rtsp-server/rtsp-server'
    target: all
  become: yes
  become_user: rtsp-server

- name: test rtsp-server
  make: 
    chdir: '/home/rtsp-server/rtsp-server'
    target: test
  become: yes
  become_user: rtsp-server

- name: install rtsp-server
  make:
    chdir: '/home/rtsp-server/rtsp-server'
    target: install
