---
- hosts: control-server
  become: true
  vars_files:
    - "{{ playbook_dir }}/vars/main_servers.yml"
  roles:
    - control-server

- hosts: main-servers
  become: true
  roles:
    - main-server
